// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicHub.Data;

#nullable disable

namespace MusicHub.Migrations
{
    [DbContext(typeof(MusicHubDbContext))]
    partial class MusicHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("MusicHub.Entities.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 3,
                            AuthorName = "",
                            Title = "Hollywood's Bleeding"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 3,
                            AuthorName = "",
                            Title = "Beerbongs & Bentleys"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 4,
                            AuthorName = "",
                            Title = "Enema Of The State"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            AuthorName = "",
                            Title = "Take Off Your Pants And Jacket"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            AuthorName = "",
                            Title = "Lost Americana"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 5,
                            AuthorName = "",
                            Title = "Tickets To My Downfall"
                        });
                });

            modelBuilder.Entity("MusicHub.Entities.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlbumId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlbumTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumId = 1,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Hollywood’s Bleeding"
                        },
                        new
                        {
                            Id = 2,
                            AlbumId = 1,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Saint‑Tropez"
                        },
                        new
                        {
                            Id = 3,
                            AlbumId = 1,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Enemies (feat. DaBaby)"
                        },
                        new
                        {
                            Id = 4,
                            AlbumId = 1,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Allergic"
                        },
                        new
                        {
                            Id = 5,
                            AlbumId = 1,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "A Thousand Bad Times"
                        },
                        new
                        {
                            Id = 6,
                            AlbumId = 1,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Circles"
                        },
                        new
                        {
                            Id = 7,
                            AlbumId = 1,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Die For Me (feat. Future & Halsey)"
                        },
                        new
                        {
                            Id = 8,
                            AlbumId = 2,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Paranoid"
                        },
                        new
                        {
                            Id = 9,
                            AlbumId = 2,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Spoil My Night (feat. Swae Lee)"
                        },
                        new
                        {
                            Id = 10,
                            AlbumId = 2,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Rich & Sad"
                        },
                        new
                        {
                            Id = 11,
                            AlbumId = 2,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Zack and Codeine"
                        },
                        new
                        {
                            Id = 12,
                            AlbumId = 2,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Takin’ Shots"
                        },
                        new
                        {
                            Id = 13,
                            AlbumId = 2,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Rockstar (feat. 21 Savage)"
                        },
                        new
                        {
                            Id = 14,
                            AlbumId = 2,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Over Now"
                        },
                        new
                        {
                            Id = 15,
                            AlbumId = 3,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Dumpweed"
                        },
                        new
                        {
                            Id = 16,
                            AlbumId = 3,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Don’t Leave Me"
                        },
                        new
                        {
                            Id = 17,
                            AlbumId = 3,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Aliens Exist"
                        },
                        new
                        {
                            Id = 18,
                            AlbumId = 3,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Going Away to College"
                        },
                        new
                        {
                            Id = 19,
                            AlbumId = 3,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "What’s My Age Again?"
                        },
                        new
                        {
                            Id = 20,
                            AlbumId = 3,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Dysentery Gary"
                        },
                        new
                        {
                            Id = 21,
                            AlbumId = 3,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Adam’s Song"
                        },
                        new
                        {
                            Id = 22,
                            AlbumId = 4,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Anthem Part Two"
                        },
                        new
                        {
                            Id = 23,
                            AlbumId = 4,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Online Songs"
                        },
                        new
                        {
                            Id = 24,
                            AlbumId = 4,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "First Date"
                        },
                        new
                        {
                            Id = 25,
                            AlbumId = 4,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Happy Holidays, You Bastard"
                        },
                        new
                        {
                            Id = 26,
                            AlbumId = 4,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Story of a Lonely Guy"
                        },
                        new
                        {
                            Id = 27,
                            AlbumId = 4,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "The Rock Show"
                        },
                        new
                        {
                            Id = 28,
                            AlbumId = 6,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Title Song"
                        },
                        new
                        {
                            Id = 29,
                            AlbumId = 6,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Kiss Kiss"
                        },
                        new
                        {
                            Id = 30,
                            AlbumId = 6,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Drunk Face"
                        },
                        new
                        {
                            Id = 31,
                            AlbumId = 6,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Bloody Valentine"
                        },
                        new
                        {
                            Id = 32,
                            AlbumId = 6,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Forget Me Too (feat. Halsey)"
                        },
                        new
                        {
                            Id = 33,
                            AlbumId = 6,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "All I Know (feat. Trippie Redd)"
                        },
                        new
                        {
                            Id = 34,
                            AlbumId = 6,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Lonely"
                        },
                        new
                        {
                            Id = 35,
                            AlbumId = 5,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Outlaw Overture"
                        },
                        new
                        {
                            Id = 36,
                            AlbumId = 5,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Cliché"
                        },
                        new
                        {
                            Id = 37,
                            AlbumId = 5,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Don’t Wait Run Fast"
                        },
                        new
                        {
                            Id = 38,
                            AlbumId = 5,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Goddamn"
                        },
                        new
                        {
                            Id = 39,
                            AlbumId = 5,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Vampire Diaries"
                        },
                        new
                        {
                            Id = 40,
                            AlbumId = 5,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Miss Sunshine"
                        },
                        new
                        {
                            Id = 41,
                            AlbumId = 5,
                            AlbumTitle = "",
                            AuthorName = "",
                            Title = "Sweet Coraline"
                        });
                });

            modelBuilder.Entity("MusicHub.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistName = "",
                            PasswordHash = "n4bQgYhMfWWaL+qgxVrQFaO/TxsrC4Is0V1sFbDwCgg=",
                            Role = "Admin",
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            ArtistName = "",
                            PasswordHash = "n4bQgYhMfWWaL+qgxVrQFaO/TxsrC4Is0V1sFbDwCgg=",
                            Role = "User",
                            UserName = "User"
                        },
                        new
                        {
                            Id = 3,
                            ArtistName = "Post Malone",
                            PasswordHash = "n4bQgYhMfWWaL+qgxVrQFaO/TxsrC4Is0V1sFbDwCgg=",
                            Role = "Musician",
                            UserName = "PostMalone"
                        },
                        new
                        {
                            Id = 4,
                            ArtistName = "Blink-182",
                            PasswordHash = "n4bQgYhMfWWaL+qgxVrQFaO/TxsrC4Is0V1sFbDwCgg=",
                            Role = "Musician",
                            UserName = "Blink182"
                        },
                        new
                        {
                            Id = 5,
                            ArtistName = "Machine Gun Kelly",
                            PasswordHash = "n4bQgYhMfWWaL+qgxVrQFaO/TxsrC4Is0V1sFbDwCgg=",
                            Role = "Musician",
                            UserName = "MachineGunKelly"
                        });
                });

            modelBuilder.Entity("MusicHub.Entities.Album", b =>
                {
                    b.HasOne("MusicHub.Entities.User", "Author")
                        .WithMany("Albums")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("MusicHub.Entities.Song", b =>
                {
                    b.HasOne("MusicHub.Entities.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("MusicHub.Entities.Album", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("MusicHub.Entities.User", b =>
                {
                    b.Navigation("Albums");
                });
#pragma warning restore 612, 618
        }
    }
}
